name: Vulnerability Report
description: Report a security vulnerability privately to the maintainers
title: "[SECURITY] "
labels: [security, triage]
assignees: [your-github-username]
body:
  - type: textarea
    id: full_report
    attributes:
      label: 🛡️ Vulnerability Report
      description: Fill out the sections in the template below (keep the headings).
      value: |
        ## 🛡️ Vulnerability Report

        **📧 Contact Information:**  
        _example@example.com_

        **📝 Summary of the Vulnerability:**  
        _Describe here_

        **🔄 Steps to Reproduce:**  
        1. Step one  
        2. Step two  

        **💥 Impact:**  
        _What’s the risk?_

        **🛠️ Suggested Mitigation:**  
        _How to fix?_
    validations:
      required: true
